// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests1 : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests1()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void Addnewcard() {
    driver.Navigate().GoToUrl("https://trello.com/b/i7iM7vXl/e2e-test");
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.LinkText("Log In")).Click();
    driver.FindElement(By.CssSelector(".label")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.CssSelector(".is-subscribe-shown .list-header-extras-menu")).Click();
    driver.FindElement(By.LinkText("Add Card…")).Click();
    driver.FindElement(By.CssSelector(".list-card-composer-textarea")).SendKeys("My new card");
    driver.FindElement(By.CssSelector(".confirm")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    {
      IReadOnlyCollection<IWebElement> elements = driver.FindElements(By.CssSelector(".active-card .list-card-title"));
      Assert.True(elements.Count > 0);
    }
    Assert.Equal(driver.FindElement(By.CssSelector(".active-card .list-card-title")).Text, "My new card");
    driver.FindElement(By.CssSelector(".active-card > .icon-sm")).Click();
    driver.FindElement(By.CssSelector(".js-archive > .quick-card-editor-buttons-item-text")).Click();
    driver.FindElement(By.CssSelector(".\\_24AWINHReYjNBf")).Click();
    driver.FindElement(By.CssSelector("li:nth-child(8) .\\_1uK2vQ_aMRS2NU")).Click();
  }
}
